/**
 * Rich Animal Facts Dataset
 * Handcrafted with verified zoological science, mind-blowing evolutionary adaptations,
 * cute quirks, and behavioral marvels.
 */

const ANIMAL_FACTS = [
  {
    id: 1,
    animal: "Wombat",
    category: "mind-blowing",
    icon: "🦔",
    tag: "Geometry Wonder",
    teaser: "Why are wombat feces the only cube-shaped droppings on Earth?",
    fact: "Wombats produce up to 100 cube-shaped droppings every night! Their intestines have alternating flexible and stiff grooves that sculpt the feces into sharp 90-degree cubes, preventing them from rolling off rocks where wombats mark their territory.",
    scientificName: "Vombatus ursinus",
    biome: "Temperate Forests & Grasslands",
    funScore: 98,
    badge: "Most Bizarre Poop"
  },
  {
    id: 2,
    animal: "Pistol Shrimp",
    category: "superpowers",
    icon: "🦐",
    tag: "Sonic Weapon",
    teaser: "A tiny 2-inch shrimp that generates temperatures hotter than the surface of the Sun!",
    fact: "When the pistol shrimp snaps its specialized claw shut at 60 mph, it creates a cavitation bubble that collapses with a sound reaching 218 decibels (louder than a gunshot) and generates temperatures exceeding 4,700°C (8,500°F)—nearly as hot as the surface of the Sun!",
    scientificName: "Alpheidae family",
    biome: "Tropical Coral Reefs",
    funScore: 100,
    badge: "Living Plasma Cannon"
  },
  {
    id: 3,
    animal: "Axolotl",
    category: "superpowers",
    icon: "🦎",
    tag: "Regeneration God",
    teaser: "Can regrow entire limbs, parts of its heart, and even sections of its brain without scarring.",
    fact: "Unlike humans who form scar tissue, the axolotl can regenerate entire severed limbs, spinal cords, retinal tissue, and portions of its brain within weeks, functioning with 100% original capacity. Scientists are mapping their 32-billion-base-pair genome for human medicine.",
    scientificName: "Ambystoma mexicanum",
    biome: "High-Altitude Freshwater Lake Xochimilco",
    funScore: 99,
    badge: "Medical Marvel"
  },
  {
    id: 4,
    animal: "Wood Frog",
    category: "survival",
    icon: "🐸",
    tag: "Cryo-Resurrection",
    teaser: "This frog literally stops its heart and freezes solid as a rock for months in winter.",
    fact: "During Alaskan winters, the Wood Frog freezes up to 70% of its body water into solid ice. Its lungs and heart stop completely, blood ceases flowing, and brain activity flatlines. Massive glucose and urea surges act as natural antifreeze inside its cells. In spring, it thaws from the inside out and hops away within hours!",
    scientificName: "Lithobates sylvaticus",
    biome: "Subarctic Tundra & Boreal Taiga",
    funScore: 99,
    badge: "Real-Life Cryonics"
  },
  {
    id: 5,
    animal: "Sea Otter",
    category: "cute",
    icon: "🦦",
    tag: "Ocean Romance",
    teaser: "Why do sea otters hold hands while they sleep?",
    fact: "Sea otters hold hands while resting in giant kelp forests (called 'rafts') so ocean currents don't drift them apart while sleeping. They also have a specialized skin pouch under their armpit where they keep their favorite rock for cracking open sea urchins and clams!",
    scientificName: "Enhydra lutris",
    biome: "North Pacific Coastal Kelp Forests",
    funScore: 100,
    badge: "Certified Adorable"
  },
  {
    id: 6,
    animal: "Mantis Shrimp",
    category: "superpowers",
    icon: "🦞",
    tag: "Hyperspectral Vision",
    teaser: "Humans have 3 color photoreceptors; the Peacock Mantis Shrimp has 16!",
    fact: "Mantis shrimp can perceive deep ultraviolet, circular polarized light, and wavelengths invisible to any other creature. Their punch accelerates at 23 m/s (matching a .22 caliber bullet), striking with 1,500 Newtons of force—strong enough to shatter aquarium glass and dismember crabs instantly.",
    scientificName: "Odontodactylus scyllarus",
    biome: "Indo-Pacific Coral Reefs",
    funScore: 97,
    badge: "Apex Puncher"
  },
  {
    id: 7,
    animal: "New Caledonian Crow",
    category: "intelligence",
    icon: "🦅",
    tag: "Tool Pioneer",
    teaser: "Crafts hooked tools, solves multi-step puzzles, and understands causal water displacement.",
    fact: "Crows can craft tools by bending twigs into hooks and cutting pandanus leaves into stepped serrated probes to harvest grubs. Experiments show they solve complex 8-stage puzzle boxes in sequence and understand Archimedes' principle, dropping stones into tubes of water to raise floating treats.",
    scientificName: "Corvus moneduloides",
    biome: "Subtropical Rainforests of New Caledonia",
    funScore: 96,
    badge: "Avian Genius"
  },
  {
    id: 8,
    animal: "Immortal Jellyfish",
    category: "ocean",
    icon: "🪼",
    tag: "Biological Immortality",
    teaser: "A creature that rewinds its age and restarts life when sick or stressed.",
    fact: "Turritopsis dohrnii can undergo cellular transdifferentiation: when aged, starved, or injured, it reverts its adult medusa cells back into juvenile polyp colonies, restarting its life cycle anew. In theory, this cycle can repeat indefinitely, making it biologically immortal!",
    scientificName: "Turritopsis dohrnii",
    biome: "Temperate to Tropical Oceans Globally",
    funScore: 98,
    badge: "Age Reverser"
  },
  {
    id: 9,
    animal: "Platypus",
    category: "mind-blowing",
    icon: "🦆",
    tag: "Frankenstein of Nature",
    teaser: "Glows biofluorescent green under UV light, lays eggs, sweats milk, and has venomous spurs!",
    fact: "The platypus has no stomach (food goes directly into intestines), hunts underwater with eyes, ears, and nostrils closed using electroreceptive sensors in its rubbery bill, secretes milk from abdominal pores rather than teats, and males possess venomous spurs on their hind legs capable of causing excruciating human pain.",
    scientificName: "Ornithorhynchus anatinus",
    biome: "Eastern Australian Freshwater Streams",
    funScore: 99,
    badge: "Nature's Mashup"
  },
  {
    id: 10,
    animal: "Greenland Shark",
    category: "ocean",
    icon: "🦈",
    tag: "Centuries Old",
    teaser: "Can live over 400 years and doesn't reach reproductive maturity until age 150!",
    fact: "Cruising at an icy 1.2 km/h in deep Arctic waters, the Greenland Shark is the longest-living vertebrate on Earth. Radiocarbon dating of eye lens proteins confirmed individuals born during the reign of King James I (early 1600s) are still swimming today!",
    scientificName: "Somniosus microcephalus",
    biome: "Arctic & North Atlantic Abyssal Depths",
    funScore: 95,
    badge: "Living Time Capsule"
  },
  {
    id: 11,
    animal: "Honey Badger",
    category: "survival",
    icon: "🦡",
    tag: "Fearless Tank",
    teaser: "Survives venomous cobra bites by simply taking a 2-hour nap, then waking up to finish its meal.",
    fact: "Honey badgers possess evolved molecular mutations in their nicotinic acetylcholine receptors that render snake neurotoxins ineffective. If bitten by a lethal puff adder or cobra, the badger falls into a comatose sleep while its immune system neutralizes the venom, waking up unharmed two hours later to eat the snake!",
    scientificName: "Mellivora capensis",
    biome: "Sub-Saharan African Savannas & Arid Scrub",
    funScore: 97,
    badge: "Invulnerability Champ"
  },
  {
    id: 12,
    animal: "Cow",
    category: "cute",
    icon: "🐮",
    tag: "Bovine Besties",
    teaser: "Cows have best friends and experience measurable anxiety when separated.",
    fact: "Scientific research conducted at the University of Northampton found that cows form tight social bonds with preferred companions. When paired with their best friend, their heart rates decrease and stress hormone levels plummet. When separated, their cortisol spikes, and milk yields drop significantly.",
    scientificName: "Bos taurus",
    biome: "Pastures & Grasslands Globally",
    funScore: 93,
    badge: "Emotional Empaths"
  },
  {
    id: 13,
    animal: "Tardigrade (Water Bear)",
    category: "survival",
    icon: "🔬",
    tag: "Cosmic Survivor",
    teaser: "Survives the vacuum of outer space, absolute zero (-273°C), and 1,000x lethal human radiation.",
    fact: "These microscopic 0.5mm champions enter 'cryptobiosis', expelling 99% of body water and producing special intrinsically disordered proteins that turn their cellular interiors into biological glass. They have survived 10 days in the vacuum and cosmic radiation of low Earth orbit on the FOTON-M3 mission!",
    scientificName: "Tardigrada phylum",
    biome: "Everywhere: Mosses, Deep Ocean Trenches, Antarctic Glaciers",
    funScore: 100,
    badge: "Space Hardy"
  },
  {
    id: 14,
    animal: "Blue Whale",
    category: "ocean",
    icon: "🐋",
    tag: "Titans of Earth",
    teaser: "Its heart weighs as much as a golf cart, and a toddler could swim through its main aorta!",
    fact: "At up to 30 meters (100 ft) and 190 metric tons, the Blue Whale is the largest animal ever known to have lived—larger than any dinosaur. Its tongue alone weighs as much as an adult African elephant, and its low-frequency vocalizations travel over 1,000 miles across entire ocean basins.",
    scientificName: "Balaenoptera musculus",
    biome: "Open Pelagic Oceans Worldwide",
    funScore: 96,
    badge: "Planetary Giant"
  },
  {
    id: 15,
    animal: "Mimic Octopus",
    category: "intelligence",
    icon: "🐙",
    tag: "Shape-Shifting Master",
    teaser: "Can actively morph its body and color into over 15 different predatory sea creatures.",
    fact: "Discovered in 1998 off Sulawesi, this cephalopod assesses nearby predators and impersonates their specific natural enemies. When harassed by damselfish, it buries six arms and displays two banded arms in opposite directions to mimic a venomous banded sea krait snake. It also impersonates lionfish, flatfish, and jellyfish!",
    scientificName: "Thaumoctopus mimicus",
    biome: "Indo-Pacific Shallow Silt Estuaries",
    funScore: 98,
    badge: "Master Impersonator"
  },
  {
    id: 16,
    animal: "Archerfish",
    category: "superpowers",
    icon: "🐟",
    tag: "Hydro-Sniper",
    teaser: "Shoots high-pressure water jets out of the water to snipe insects from branches 2 meters up!",
    fact: "The archerfish forms a gun barrel by pressing its tongue against a groove on the roof of its mouth. It calculates light refraction between water and air, adjusts water volume for distance, and fires a pulse that accelerates mid-air so the water blob hits the insect like a punch, knocking it into the water in milliseconds.",
    scientificName: "Toxotes jaculatrix",
    biome: "Southeast Asian Mangroves & Estuaries",
    funScore: 94,
    badge: "Laser Accuracy"
  },
  {
    id: 17,
    animal: "African Elephant",
    category: "intelligence",
    icon: "🐘",
    tag: "Seismic Hearers",
    teaser: "Elephants can 'hear' thunderstorms 150 miles away through their feet!",
    fact: "Elephants have specialized mechanoreceptors called Pacinian corpuscles packed in the skin of their foot pads. When a herd stomps or distant lightning strikes, low-frequency seismic vibrations travel through the soil and up the elephant's skeleton to its middle ear, allowing herds to divert toward rains hundreds of miles away.",
    scientificName: "Loxodonta africana",
    biome: "African Savannas & Woodlands",
    funScore: 98,
    badge: "Seismic Radar"
  },
  {
    id: 18,
    animal: "Lyrebird",
    category: "mind-blowing",
    icon: "🦚",
    tag: "Sonic Photocopier",
    teaser: "Can perfectly replicate car alarms, chainsaws, crying babies, and camera shutters.",
    fact: "The Australian Superb Lyrebird possesses the most complex syrinx (vocal organ) of all songbirds. Males spend years memorizing and mimicking the sounds of their forest environment: other bird species, roaring chainsaws, camera shutters with motor drives, car alarms, and barking dogs, performing them to woo mates.",
    scientificName: "Menura novaehollandiae",
    biome: "Southeastern Australian Temperate Rainforests",
    funScore: 96,
    badge: "Nature's Synthesizer"
  },
  {
    id: 19,
    animal: "Naked Mole-Rat",
    category: "survival",
    icon: "🐁",
    tag: "Cancer-Resistant",
    teaser: "Feels almost zero pain from acid, rarely gets cancer, and lives 30+ years underground.",
    fact: "Naked mole-rats live in subterranean eusocial colonies like ants with a single queen. Their cells produce extremely dense high-molecular-mass hyaluronan (HMM-HA), which prevents tumors from developing. They can also survive 18 minutes in pure nitrogen without any oxygen by switching to fructose metabolism!",
    scientificName: "Heterocephalus glaber",
    biome: "East African Arid Subterranean Burrows",
    funScore: 95,
    badge: "Biological Super-Soldier"
  },
  {
    id: 20,
    animal: "Quokka",
    category: "cute",
    icon: "🦘",
    tag: "Happiest Animal",
    teaser: "Known as the world's happiest animal due to its permanent friendly grin.",
    fact: "Native to Rottnest Island in Western Australia, quokkas evolved with few natural predators. They possess zero innate fear of humans and hop up curious and cheerful. Their skull anatomy and curved jawline naturally position their mouth into a bright smile, earning them global fame as the selfie icons of the animal kingdom.",
    scientificName: "Setonix brachyurus",
    biome: "Rottnest Island Coastal Scrub",
    funScore: 99,
    badge: "Pure Joy"
  }
];

window.ANIMAL_FACTS = ANIMAL_FACTS;
